baseURL = "https://eglises-ouvertes.ch/"
canonifyURLs = true
cleanDestinationDir = true
copyright = "CC0 (domaine public)"
date = [ "date", "lastmod" ]
defaultContentLanguage = "fr"
disableFastRender = true
disableKinds = [ "RSS", "robotsTXT", "taxonomy", "term", "404" ]
languageCode = "fr"
lastmod = [ "lastmod", ":git" ]
removePathAccents = true
title = "Églises ouvertes"