description = "édifices protestants réformés en Suisse romande"
images = [
  "https://pixabay.com/fr/photos/l%c3%a9ger-chapelle-%c3%a9glise-architecture-3176887/",
  "https://pixabay.com/fr/photos/%c3%a9glise-islande-l-%c3%a9glise-noire-4964183/"
]
footer = """
Ce site est une sauvegarde de eglises-ouvertes.ch. Les données sont livrées sans garantie.

**Responsable:** ~~Joël Burri~~ site abandonné     
**Créateur du site initial:** [Nicolas Friedli](https://nicolasfriedli.ch)  
**Licence:** Creative Commons Zero (CC0) / **Code source:** [GitHub](https://github.com/nfriedli/eglises-ouvertes)  
"""

