description = "édifices protestants réformés en Suisse romande"

footer = """
**Responsable:** [Nicolas Friedli](https://nicolasfriedli.ch)  
**Licence:** Creative Commons Zero (CC0) / **Code source:** [GitHub](https://github.com/nfriedli/eglises-ouvertes)  
"""

