minifyOutput = true

[tdewolff.css]
keepCSS2 = false

[tdewolff.html]
keepConditionalComments = false
keepDefaultAttrVals = false
keepEndTags = false
keepQuotes = true
keepWhitespace = true


[tdewolff.js]
keepVarNames = true

[tdewolff.json]
keepNumbers = true